version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb

    volumes:
      - data:/data/db

  node_app:
    build: ./backend
    image: node_app_image:latest
    container_name: node_app

    ports:
      - "3001:3001"

    depends_on:
      - mongodb

  react_app:
    build: ./frontend
    image: react_app_image:latest
    container_name: react_app

    ports:
      - "3000:3000"

    depends_on:
      - node_app

volumes:
  data:
